version: '3.4'

services:

  web:
    command: ./run_web.sh
    volumes:
      - static:/static
    env_file:
      - docker.env
    environment:
      - APP_ENV=PRODUCTION
      - DJANGO_SETTINGS_MODULE=altuntas.settings.production

  nginx:
    container_name: nginx
    command: wait-for web:8000 -- nginx -g "daemon off;"
    depends_on:
      - web
    image: nginx:alpine
    networks:
      - main
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/altuntas/wait-for:/bin/wait-for
      - static:/var/www/app/static

volumes:
  static: