# Generated by Django 3.2.5 on 2021-07-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('favourite_count', models.IntegerField()),
                ('author', models.TextField()),
                ('created_date', models.DateTimeField()),
                ('edited_date', models.DateTimeField(blank=True)),
                ('eksisozluk_entry_id', models.IntegerField(unique=True)),
                ('eksisozluk_author_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Eksisozluk Entry',
                'verbose_name_plural': 'Eksisozluk Entries',
                'db_table': 'web_eksisozluk_entries',
            },
        ),
    ]
