# Generated by Django 3.2.5 on 2021-07-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='entry',
            table='scraper_eksisozluk_entries',
        ),
    ]
